implementing random forests : random forests in python . breiman, 2001

In [ ]:
#After a large number of trees is generated, they vote for the most popular class. We call these procedures random forests.

##implementing desicion tree before random forest

In [ ]:
#when we have complex dataset we cant draw a single line we need to split our datset again and again to come up with decision boundry
#choose attributes for node that provides- low entropy , it leads to high information gain

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\ML_LABS\CSVs used\salaries.csv")

In [8]:
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [13]:
df.columns

Index(['company', 'job', 'degree', 'salary_more_then_100k'], dtype='object')

In [15]:
inputs = df.drop('salary_more_then_100k',axis= 'columns')
inputs

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [18]:
target =df['salary_more_then_100k']
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

Convert the text columns into numeric columns before training. Scikit-learn models cannot fit directly on strings.

In [ ]:
inputs_encoded = pd.get_dummies(inputs, columns=['company', 'job', 'degree'], dtype=int)
inputs_encoded

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier(random_state=42)
model.fit(inputs_encoded, target)

In [ ]:
model.score(inputs_encoded, target)